DEBUG = False

DATABASE_USER = 'CHANGME'
DATABASE_NAME = 'CHANGME'
DATABASE_PASS = 'CHANGME'
SECRET_KEY = 'CHANGE ME'
THUNDERFOREST_API_KEY = 'yourAPIKey'
OPENATLAS_URL = 'https://url_to_database_backend + /entity/'
